-- CRIAR UM BD PARA EXERCICIO DA SEMANA 07

CREATE DATABASE SEMANA07;

-- SELECIONAR A INSTANCIA DO BD CRIADO
USE SEMANA07;

-- CRIAR UMA TABELA CLIENTES COM OS ATRIBUTOS ID, NOME, TELEFONE E ENDERECO EXERCICIO 1

CREATE TABLE CLIENTES
(
Id       INT PRIMARY KEY,
Nome     VARCHAR (25),
TELEFONE VARCHAR (11),
ENDERECO VARCHAR (25)
);

-- CRIAR UM SCRIPT PARA INSERIR 3 CLIENTES EXERCICIO 2

INSERT INTO CLIENTES (ID, NOME, TELEFONE, ENDERECO) VALUES (1,'vinicius Silva', 987654,'Rua Girassol');
INSERT INTO CLIENTES (ID, NOME, TELEFONE, ENDERECO) VALUES (2, 'Maria Antonia', 123456,'Rua Rosas');
INSERT INTO CLIENTES (ID, NOME, TELEFONE, ENDERECO) VALUES (3, 'Marcus Vinicius', 654123, 'Rua Itajai');

-- CRIAR UM SCRIPT PARA SELECIONAR TODOS OS CLIENTES EXERCICIO 3

SELECT *FROM CLIENTES

-- CRIAR UM SCRIPT PARA SELECIONAR OS CLIENTES FILTRANDO PELO CAMPO ID EXERCICIO 4

SELECT ID, NOME FROM CLIENTES

-- CRIAR UM SCRIPT QUE FILTRE OS CLIENTES USANDO LIKE '%%' EXERCICIO 5

SELECT * FROM CLIENTES
WHERE NOME like '%a%'

-- CRIAR UM SCRIPT PARA ATUALIZAR O ENDEREÇO DO MARCUS VINICIUS PARA RUA DO LIMÃO EXERCICIO 6

UPDATE CLIENTES
SET ENDERECO = 'Rua do Limão'
WHERE ID = 3


-- CRIAR O SCRIPT PARA EXCLUIR O CLIENTE ID 2 EXERCICIO 7

DELETE CLIENTES
WHERE ID = 2

