-- CRIAÇÃO DE NOVO BANCO DE DADOS PARA SEMANA 07 EXERCICIO 8
CREATE DATABASE SM07_EXERCICIO8
-- MUDAR A INSTANCIA
USE SM07_EXERCICIO8 

-- DROPAR BANCO DE DADOS
DROP DATABASE SM07_EXERCICIO8 

-- CRIAR A TABELA CONFORME ATRIBUROS DISPONIBILIZADOS NO EXERCICIO (TABELA NAO NORMALIZADA) 

CREATE TABLE FUNCIONARIO_NFN
(
ID INT IDENTITY (1,1) PRIMARY KEY,
NOME VARCHAR (50),
CARGO VARCHAR (50),
TEL1 VARCHAR (7),
TEL2 VARCHAR (8)
)

-- INCLUIR OS REGISTROS CONFORME DADOS DISPONIBILIZADOS NO EXERCICIO NA TABELA NÃO NORMALIZADA
INSERT INTO FUNCIONARIO_NFN (NOME, CARGO, TEL1, TEL2) VALUES ('Marcos', 'Atendente', '3654589', '32645987')
INSERT INTO FUNCIONARIO_NFN (NOME, CARGO, TEL1, TEL2) VALUES ('Maria', 'Gerente', '3654698', '36524569')
INSERT INTO FUNCIONARIO_NFN (NOME, CARGO, TEL1, TEL2) VALUES ('Julia', 'Atendente', '3654962', '12365458')

-- SELEÇÃO DOS DADOS INSERIDOS PARA CONFERÊNCIA
SELECT * FROM FUNCIONARIO_NFN

-- PRIMEIRA E SEGUNDA FORMA NORMAL (CRIADO UMA TABELA PARA O TELEFONE, ELIMANDO ESSES CAMPOS DA PRINC, FEITO A REFERÊNCIA COM O ID DA TABELA PRINCIPAL, ACRESCENTADO NN NAS CONSTRAINT)
-- E ALTERADO A TABELA TELEFONE FAZENDO PK NOS 2 CAMPOS

CREATE TABLE FUNCIONARIO_FN1
(
ID INT IDENTITY (1,1) PRIMARY KEY,
NOME VARCHAR (50),
CARGO VARCHAR (50),
)

CREATE TABLE TELEFONE_FN1(
ID INT REFERENCES FUNCIONARIO_FN1(ID) NOT NULL ,
TELEFONE VARCHAR(11) NOT NULL 
)

ALTER TABLE TELEFONE_FN1 ADD PRIMARY KEY (ID, TELEFONE)

-- INCLUIR OS REGISTROS CONFORME DADOS DISPONIBILIZADOS NO EXERCICIO NA TABELA NA PRIMEIRA FORMA NORMAL (OBSERVANDO OS ATRIBUTOS)

INSERT INTO FUNCIONARIO_FN1 (NOME, CARGO) VALUES ('Marcos', 'Atendente')
INSERT INTO FUNCIONARIO_FN1 (NOME, CARGO) VALUES ('Maria', 'Gerente')
INSERT INTO FUNCIONARIO_FN1 (NOME, CARGO) VALUES ('Julia', 'Atendente')

-- SELEÇÃO DOS DADOS INSERIDOS PARA CONFERÊNCIA DA TABELA FUNCIONARIO 

SELECT * FROM FUNCIONARIO_FN1

-- INCLUIR OS DEMAIS REGISTROS, NA OUTRA TABELA CRIADA (OBSERVAR OS ATRIBUTOS)

INSERT INTO TELEFONE_FN1 (ID, TELEFONE) VALUES (1,'3654589')
INSERT INTO TELEFONE_FN1 (ID, TELEFONE) VALUES (1,'32645987')
INSERT INTO TELEFONE_FN1 (ID, TELEFONE) VALUES (2,'3654698')
INSERT INTO TELEFONE_FN1 (ID, TELEFONE) VALUES (2,'36524569')
INSERT INTO TELEFONE_FN1 (ID, TELEFONE) VALUES (3,'3654962')
INSERT INTO TELEFONE_FN1 (ID, TELEFONE) VALUES (3,'12365458')

-- SELEÇÃO DOS DADOS INSERIDOS PARA CONFERÊNCIA DA TABELA TELEFONE

SELECT * FROM TELEFONE_FN1

-- SELEÇÃO DOS DADOS DAS 2 TABELAS JUNTAS
SELECT * FROM FUNCIONARIO_FN1
SELECT * FROM TELEFONE_FN1

-- TERCEIRA FORMA NORMAL (COPIA TUDO DA PRIMEIRA E CRIADO UMA TABELA PARA O CARGO, FEITO A REFERÊNCIA COM O ID DA TABELA PRINCIPAL, ACRESCENTADO NN NAS CONSTRAINT)
-- ALTERADO O NOME DA TABELAS

CREATE TABLE CARGO_FN2(
	ID INT PRIMARY KEY, 
	CARGO VARCHAR(50)
)

CREATE TABLE FUNCIONARIO_FN2
(
ID INT IDENTITY (1,1) PRIMARY KEY,
NOME VARCHAR (50),
CARGO_ID INT REFERENCES CARGO_FN2 (ID),
)

CREATE TABLE TELEFONE_FN2(
ID INT REFERENCES FUNCIONARIO_FN2(ID) NOT NULL ,
TELEFONE VARCHAR(11) NOT NULL 
)

ALTER TABLE TELEFONE_FN2 ADD PRIMARY KEY (ID, TELEFONE)

-- INCLUIR OS REGISTROS CONFORME DADOS DISPONIBILIZADOS NO EXERCICIO NA TABELA CARGO (OBSERVANDO OS ATRIBUTOS)

INSERT INTO CARGO_FN2 (ID, CARGO) VALUES (1,'Atendente')
INSERT INTO CARGO_FN2 (ID, CARGO) VALUES (2,'Gerente')


-- SELEÇÃO DOS DADOS INSERIDOS PARA CONFERÊNCIA DA TABELA CARGO_FN2
SELECT * FROM CARGO_FN2

-- INCLUIR OS REGISTROS, NA TABELA FUNCIONÁRIO (OBSERVAR OS ATRIBUTOS)
INSERT INTO FUNCIONARIO_FN2(NOME,CARGO_ID) VALUES ('Marcos', 1)
INSERT INTO FUNCIONARIO_FN2 (NOME, CARGO_ID) VALUES ('Maria', 2)
INSERT INTO FUNCIONARIO_FN2 (NOME, CARGO_ID) VALUES ('Julia', 1)

-- SELEÇÃO DOS DADOS INSERIDOS PARA CONFERÊNCIA DA TABELA FUNCIONARIO_FN2
SELECT * FROM FUNCIONARIO_FN2

-- INCLUIR OS DEMAIS REGISTROS, NA OUTRA TABELA CRIADA (OBSERVAR OS ATRIBUTOS)
INSERT INTO TELEFONE_FN2 (ID, TELEFONE) VALUES (1,'3654589')
INSERT INTO TELEFONE_FN2 (ID, TELEFONE) VALUES (1,'32645987')
INSERT INTO TELEFONE_FN2 (ID, TELEFONE) VALUES (2,'3654698')
INSERT INTO TELEFONE_FN2 (ID, TELEFONE) VALUES (2,'36524569')
INSERT INTO TELEFONE_FN2 (ID, TELEFONE) VALUES (3,'3654962')
INSERT INTO TELEFONE_FN2 (ID, TELEFONE) VALUES (3,'12365458')

-- SELEÇÃO DOS DADOS INSERIDOS PARA CONFERÊNCIA DA TABELA TELEFONE

SELECT * FROM TELEFONE_FN2

-- SELEÇÃO DOS DADOS DAS 3 TABELAS JUNTAS

SELECT * FROM CARGO_FN2
SELECT * FROM FUNCIONARIO_FN2
SELECT * FROM TELEFONE_FN2
